version: '3'

services:
  front-end:
    build: front-end/
    container_name: baere_front_end
    working_dir: /app
    volumes: 
      - ./front-end:/app
    stdin_open: true
    tty: true
    command: sh
    ports: 
      - 3000:3000
    restart: on-failure

